image: python:3

cache:
  paths:
    - .pip

before_script:
  - mkdir -p .pip
  - pip install -U pip
  - pip --cache-dir=.pip install -r requirements.txt
  - pip --cache-dir=.pip install pytest

tests:
  script:
    - python3 -m pytest
